config/routes.rb
Rails.application.routes.draw do
  get '/closure_notice', as: :closure_notice, to: 'notices#closure_notice'
  resources :log_entry, only: [:create]
  devise_for :suppliers, controllers: { registrations: "suppliers/registrations" }
  resources :places, only: [:index, :show]
  resources :promotion, only: [:index]
  resources :about, only: [:index]
  resources :suggest, only: [:index]
  resources :legal, only: [:index]
  resources :privacy, only: [:index]
  resources :unsubscribed, only: [:index]
  resources :journeys, only: [:index] do
    collection do
      get ':from/(:to)' => 'journeys#index', as: :from_to
      get ':from/:to/bookings/new' => 'bookings#new', as: :new_booking
      get ':from/:to/return' => 'journeys#return', as: :return
    end
  end
  resources :bookings, only: [:new, :create, :destroy] do
    collection do
      post :price
      post :passengers
      get :confirmation
      get :edit
      put :update
    end
    member do
      get :return_journeys
      put :send_missed_feedback
    end
  end
  
  resources :stops do
    resources :landmarks, only: [:index]
  end
  
  resources :routes

  root 'public#index'

  namespace :admin do
    get 'pending' => 'suppliers#pending'
    root 'journeys#index'
    #resource :team, only: [:show]
    resources :teams
    resources :pricing_rules
    get :account, to: 'teams#show'
    resources :journeys do
      collection do
        get 'surrounding_journeys'
      end
      member do
        post 'send_message'
      end
      resources :bookings, only: [:show, :update]
    end
    resources :bookings
    resources :suppliers
    resources :routes do
      member do
        put 'sort'
      end

      resources :stops
      resources :sub_routes
    end
    resources :suggestions
    resources :supplier_suggestions
    resources :promo_codes
    resources :bookings, only: :show
    resources :sms, only: [:new, :create]
    resources :places, only: [:new, :create]
    resources :placenames, only: [:index]
    resources :timetables
  end
  get '/admin' => 'admin/journeys#index', as: :supplier_root # creates user_root_path
  get '/bookings/:token/cancel', as: :cancel_booking, to: 'bookings#cancel'
  get '/bookings/cancelled', as: :booking_cancelled
  
end

app/models/journey.rb
require 'csv'

class Journey < ApplicationRecord
  belongs_to :route
  has_many :stops, through: :route
  has_many :outward_bookings, dependent: :destroy, class_name: 'Booking', foreign_key: 'journey_id'
  has_many :return_bookings, dependent: :destroy, class_name: 'Booking', foreign_key: 'return_journey_id'
  has_many :bookings, dependent: :destroy, class_name: 'Booking'
  belongs_to :team
  validates_presence_of :team, :start_time, :route
  
  attr_accessor :pickup_stop, :dropoff_stop

  scope :forwards, -> {where("reversed IS NOT TRUE")}
  scope :backwards, -> {where("reversed IS TRUE")}
  scope :available, -> {where('start_time > :start_time AND open_to_bookings IS TRUE AND "full?" IS FALSE', start_time: Time.now)}

  scope :past_or_future, ->(past_or_future) {
    if past_or_future == 'past'
      where('start_time < ?', Time.now).order('start_time DESC')
    elsif past_or_future == 'future'
      where('start_time > ?', Time.now).order('start_time ASC')
    end
  }
  
  scope :on_date, ->(date) {
    where('start_time >= ? AND start_time <= ?', date.to_date.at_beginning_of_day, date.to_date.at_end_of_day)
  }
  scope :booked_or_empty, ->(booked_or_empty) {
    query = joins('LEFT JOIN bookings as outward_bookings on journeys.id = outward_bookings.journey_id LEFT JOIN bookings as return_bookings on journeys.id = return_bookings.return_journey_id').group('journeys.id')
    booked_or_empty == 'booked' ? query.having('count(outward_bookings) > 0 OR count(return_bookings) > 0') : query.having('count(outward_bookings) = 0 AND count(return_bookings) = 0')
  }
  scope :by_route, ->(route_id) {
    where(route_id: Route.id_with_subroutes(route_id))
  }

  filterrific(
    default_filter_params: {
      past_or_future: 'future'
    },
    available_filters: [
      :past_or_future,
      :on_date,
      :booked_or_empty,
      :by_route
    ]
  )
  
  after_create :close_before_end
  after_update :change_close_time, if: :saved_change_to_start_time?
  
  def self.available_for_places(start_place, destination_place)
    from = Stop.where(place: start_place)
    to = Stop.where(place: destination_place)
    routes = Route.where(id: from.collect(&:route_id) & to.collect(&:route_id)).includes(:stops)
    journeys = routes.map do |route|
      stops = route.stops
      f = from.find { |s| stops.include?(s) }
      t = to.find { |s| stops.include?(s) }
      Journey.available.where(
        route_id: route.id,
        reversed: f.position > t.position,
      ).pluck(:id)
    end.flatten.uniq
    Journey.where(id: journeys)
  end
  
  def duplicate(start_date, end_date, include_days = [0,1,2,3,4,5,6])
    (start_date..end_date).each do |date|
      next unless include_days.include?(date.wday)
      Journey.create(attributes.except('id').merge({
        'start_time' => "#{date.to_s}T#{start_time.strftime('%H:%M')}"
      }))
    end
  end

  def booked_bookings
    bookings.booked
  end

  def editable_by_supplier?(supplier)
    supplier.team == self.team
  end

  def is_booked?
    all_bookings.count > 0
  end

  def seats_left
    seats - booked_bookings.sum(:number_of_passengers)
  end

  def route_name
    "#{stops_in_direction.first.name} - #{stops_in_direction.last.name}"
  end

  def stops_in_direction
    reversed? ? stops.reverse : stops
  end
  
  def time_at_stop(stop)
    start_time + stop.minutes_from_first_stop(reversed?).minutes
  end
  
  def all_bookings
    outward_bookings.booked + return_bookings.booked
  end
  
  def csv
    CSV.generate do |csv|
      csv << csv_headers
      all_bookings.each do |booking|
        csv << booking.csv_row(id)
      end
    end
  end
  
  def csv_headers
    Booking.csv_headers + [
      'Outbound or Return',
      'Pickup Time',
      'Pickup Place',
      'Pickup Location',
      'Dropoff Time',
      'Dropoff Place',
      'Dropoff Location'
    ]
  end
  
  def filename
    [
      stops_in_direction.first.name.downcase,
      stops_in_direction.last.name.downcase,
      start_time.strftime('%F')
    ].join('-')
  end
  
  private
    
    def close_time
      if start_time.hour < 9
        (start_time - 1.day).change({ hour: 15, min: 30 })
      else
        start_time - 4.hours
      end
    end
    
    def close_before_end
      CloseBeforeEnd.enqueue(id, run_at: close_time)
    end
    
    def change_close_time
      QueJob.where("args::json->>0 = '?' AND job_class = 'CloseBeforeEnd'", id).destroy_all
      close_before_end
    end

end

app/controllers/admin/journeys_controller.rb
class Admin::JourneysController < AdminController
  before_action :find_journey, only: [:edit, :update, :destroy, :show, :send_message]
  before_action :check_permissions, except: [:index, :create, :new, :show, :surrounding_journeys]
  def index
    journeys = (current_supplier.admin? ? Journey.all : current_team.journeys).includes([:team, :route])
    @filterrific = initialize_filterrific(
      journeys,
      (params[:filterrific] || {})
    ) or return
    @journeys = @filterrific.find.page(params[:page])
    @routes = Route.main_routes
  end

  def new
    if params[:route_id]
      @route = Route.find(params[:route_id])
      @journey = current_team.journeys.new(route: @route, reversed: params[:reversed])
      @back_path = new_admin_journey_path
    else
      @back_path = admin_root_path
      render template: 'admin/journeys/new_choose_route'
    end
  end

  def create
    journey = Journey.create!(journey_params)
    redirect_to admin_journeys_path
  end

  def edit
    @back_path = admin_journey_path(@journey)
  end

  def show
    @back_path = admin_root_path
    respond_to do |format|
      format.html
      format.csv { send_data @journey.csv, filename: "#{@journey.filename}.csv", type: 'text/csv;charset=utf-8' }
    end
  end

  def update
    @journey.update_attributes(journey_params)
    redirect_to admin_journey_path(@journey)
  end

  def destroy
    @journey.destroy
    redirect_to admin_journeys_path
  end

  # TODO: What does this do? This should be moved to the RoutesController anyway
  def surrounding_journeys
    @route = Route.find(params[:route_id])
    @previous_journeys = @route.journeys.where('start_time < ?', params[:datetime]).order('start_time DESC').limit(2)
    @next_journeys = @route.journeys.where('start_time > ?', params[:datetime]).order('start_time ASC').limit(2)
    render layout: false
  end

  def send_message
    bookings = params[:to] == 'all' ? @journey.bookings : [ @journey.bookings.find(params[:to]) ]
    bookings.each do |booking|
      SendSMS.enqueue(to: booking.phone_number, message: params[:notification_message])
    end
    flash[:notice] = "Message sent!"
    redirect_to admin_journey_path(@journey)
  end

  private

  def journey_params
    params.require(:journey).permit(:start_time, :team_id, :route_id, :open_to_bookings, :reversed, :seats)
  end

  def find_journey
    @journey = Journey.find(params[:id])
  end

  def check_permissions
    unless @journey.editable_by_supplier?(current_supplier)
      render :file => "public/401.html", :status => :unauthorized
    end
  end
end

app/controllers/journeys_controller.rb
class JourneysController < PublicController
  before_action :find_places
  respond_to :html, :js
  
  def index
    if @from && @to
      @journeys = Journey.available_for_places(@from, @to)
      if @to.routes.count == 0 || @journeys.count == 0
        @possible_destinations = Place.possible_destinations(@from).uniq
        TrackFailedPlaceQuery.enqueue(@from.name, @to.name, DateTime.now.to_s)
      end
    end
  end
  
  def return
    start_time = DateTime.parse params[:start_time]
    @booking = Booking.new
    @journeys = Journey.available_for_places(@to, @from)
                       .where(start_time: start_time...start_time.end_of_day)
                       .order(:start_time)
  end
  
  private
  
    def journey_params
      params.permit(:from, :to)
    end
    
    def find_places
      @from = Place.friendly.find(journey_params[:from]) if journey_params[:from]
      @to = Place.friendly.find(journey_params[:to]) if journey_params[:to]
    end
  
end

app/views/admin/journeys/_fields.html.haml
.surrounding_journeys
= form.label :start_time, "Select Date & Time"
= form.text_field :start_time, value: Time.now.strftime("%d/%m/%Y %H:%M")
- if current_supplier.admin?
  = form.label :team_id, 'Team'
  = form.select :team_id, options_from_collection_for_select(Team.all, 'id', 'name'), { selected: current_team.id }, class: 'select'
- else
  = form.hidden_field :team_id, value: current_team.id
= form.label :seats, 'Number of available seats'
= form.number_field :seats
= form.label :open_to_bookings, "Open to Bookings?"
= form.check_box :open_to_bookings
- content_for :js do
  :javascript
    $('#journey_start_time').datetimepicker({
      format:'d/m/Y H:i'
    });

    $(function() {
      $('#journey_start_time').change(function() {
        $.get(
          '#{surrounding_journeys_admin_journeys_path}',
          {
            datetime: $('#journey_start_time').val(),
            route_id: $('input[name=\'journey[route_id]\']:checked').val()
          },
          function(html) {
            $('.surrounding_journeys').html(html);
          }
        )
      })
    })

app/views/admin/journeys/_journey.html.haml
= link_to admin_journey_path(journey), class: "card journey" do
  %div{:class => "#{" past-journey" if journey.start_time.past?}#{journey.team == current_team ? " my-journey" : " team-journey"}", "data-booked" => "if journey.is_booked? true else false", :id => "jrny_#{journey.id}"}
    %ul
      %li
        = friendly_date journey.start_time
        = journey.start_time.strftime("%H:%M")
      %li= journey.route.name
      %li
        %span.number= journey.all_bookings.count
        = "booking".pluralize(journey.all_bookings.count)

app/views/admin/journeys/_journeys.html.haml
#filterrific_results
  - if @journeys.exists?
    = render partial: 'admin/journeys/journey', collection: @journeys
  - else
    .card.journey
      %p
        There are no journeys to be found here either try another filter, or #{link_to "add a new journey", new_admin_journey_path} now to get started.
  = paginate @journeys

app/views/admin/journeys/edit.html.haml
.container
  .inner
    .card.no-click.wide-btn
      = form_for [:admin, @route, @journey] do |form|
        .inner
          %h4 Edit Journey
          = render partial: 'fields', locals: {form: form}
        .half
          = form.submit "Save Edit", :class => "button border-bottom-left-radius"
      .half
        = form_for [:admin, @route, @journey], method: :delete do |form|
          = form.submit "Delete journey", :class => "negative button border-bottom-right-radius"

app/views/admin/journeys/index.html.haml
%section.section
  .card
    %h2 Journeys
    - if !current_team.solo_team?
      #admin-team-filter.inline
        %h4
          - if params[:filter] == 'team'
            %strong Team's Journeys
            = link_to admin_journeys_path(filterrific: params[:filterrific]) do
              My Journeys
          - else
            %strong My Journeys
            = link_to admin_journeys_path(filter: 'team', filterrific: params[:filterrific]) do
              Team's Journeys
              
    = form_for_filterrific @filterrific do |form|
      = form.label :on_date, 'Filter by Date'
      = form.date_field :on_date, value: @filterrific.on_date
      
      = form.label :by_route, 'Filter by routes'
      = form.select :by_route, options_from_collection_for_select(@routes, :id, :name, @filterrific.by_route), { include_blank: 'All Routes' }, { class: 'select' }
      .hidden
        = hidden_field_tag :filter, params[:filter]
        = form.select(:past_or_future, [['Past', 'past'], ['Future', 'future'],],{ include_blank: '- Any -' })
        = form.select(:booked_or_empty, [['Booked', 'booked'], ['Empty', 'empty'],],{ include_blank: '- Any -' })
        = submit_tag "Update filter", name: nil

    #admin-journey-filters.tabs
      #booked_or_empty.tabs-container.three-tabs
        %div{:class => "tab radius border-left-radius#{" selected" if @filterrific.booked_or_empty == nil}", "data-tabid" => ""}
          All
        %div{:class => "tab#{" selected" if @filterrific.booked_or_empty == 'booked'}", "data-tabid" => "booked"}
          Booked
        %div{:class => "tab radius border-right-radius#{" selected" if @filterrific.booked_or_empty == 'empty'}", "data-tabid" => "empty"}
          Empty
      #past_or_future.tabs-container
        %div{:class => "tab radius border-left-radius#{" selected" if @filterrific.past_or_future == 'future'}", "data-tabid" => "future"}
          Upcoming
        %div{:class => "tab radius border-right-radius#{" selected" if @filterrific.past_or_future == 'past'}", "data-tabid" => "past"}
          Past
    
    = render partial: 'admin/journeys/journeys'

    .action.primary
      = link_to new_admin_journey_path do
        .button Add a journey

- content_for :js do
  :javascript
    $(document).ready(function() {
      $('.tab').click(function() {
        if ($(this).hasClass('selected')) {
          var parentID = $(this).parent().attr('id');
          $('#filterrific_' + parentID).val($(this).data('tabid'));
          $('#filterrific_' + parentID).change();
        }
      });
    });

app/views/admin/journeys/index.js.erb
$("#filterrific_results").html("<%= escape_javascript render(partial: 'admin/journeys/journeys') %>");

app/views/admin/journeys/new.html.haml
%section.section
  = form_for [:admin, @journey] do |form|
    .card
      %h2 Add a new journey
      %p.highlight= @journey.route_name
      %p
        Via #{@journey.stops_in_direction.count-2} Possible Stops:
      %ul
        - @journey.stops_in_direction[1..-2].each_with_index do |stop|
          %li= stop.name
      %select.waypoints{:id => "select_#{@route.id}", :multiple => "multiple", :style => "display:none;"}
        - @journey.stops_in_direction.each do |stop|
          %option{:selected => "selected", :value => "#{stop.place.latitude}, #{stop.place.longitude}"}= stop.name
      .route_preview{:id => "map_#{@route.id}"}
      %section.section
        = form.hidden_field 'route_id'
        = form.hidden_field 'reversed'
        = render partial: 'fields', locals: {form: form}
        .action.primary
          = form.submit "Create Journey", :class => "button"
- content_for :js do
  :javascript
    function initMap() {
      $('.route_preview').each(function(i, m) {
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        var map = new google.maps.Map(m, {
          scrollwheel:  false,
          disableDefaultUI: true,
          scaleControl: true,
          draggable: false
        });
        directionsDisplay.setMap(map);

        calculateRouteMultiStop(directionsService, directionsDisplay, $(this));
      });
    }

app/views/admin/journeys/new_choose_route.html.haml
%section.section
  - if Route.exists?
    - Route.bookable_routes.each do |route|
      .card
        %h2 Select a Route
        %p= route.name 
        Via
        %ul
          - route.stops.each_with_index do |stop|
            %li= stop.name
          %li= link_to "create forwards journey", new_admin_journey_path(route_id: route.id, reversed: false)
        %ul
          - route.stops.reverse.each_with_index do |stop|
            %li= stop.name
          %li= link_to "create backwards journey", new_admin_journey_path(route_id: route.id, reversed: true)
        %select.waypoints{:id => "select_#{route.id}", :multiple => "multiple", :style => "display:none;"}
          - route.stops.each do |stop|
            %option{:selected => "selected", :value => "#{stop.place.latitude}, #{stop.place.longitude}"}= stop.name
        .route_preview{:id => "map_#{route.id}"}
  - else
    %p There are currently no routes, please check back again later for more routes to be added.
- content_for :js do
  :javascript
    function initMap() {
      $('.route_preview').each(function(i, m) {
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        var map = new google.maps.Map(m, {
          scrollwheel:  false,
          disableDefaultUI: true,
          scaleControl: true,
          draggable: false
        });
        directionsDisplay.setMap(map);

        calculateRouteMultiStop(directionsService, directionsDisplay, $(this));
      });
    }

app/views/admin/journeys/show.html.haml
%section.section
  .card
    %h2= @journey.route.name
    %p= @journey.start_time.to_s(:long)
    %h3 Stops:
    %p
      - @journey.stops.includes([:place, :route]).each do |stop|
        %p
          = stop.name
          \:
          \#{@journey.time_at_stop(stop).strftime("%H:%M")}
    - if @journey.editable_by_supplier?(current_supplier)
      %p= link_to 'Edit', edit_admin_journey_path(@journey), class: 'button border-bottom-radius'
    - if @journey.is_booked?
      %h3 Bookings:
      - @journey.all_bookings.each do |booking|
        .card
          %h4
            #{booking.pickup_stop.name} to #{booking.dropoff_stop.name}
          %p= pluralize booking.number_of_passengers, "Passenger"
          %p
            Tel: #{booking.phone_number}
        
          =link_to 'Show booking', admin_journey_booking_path(@journey, booking)
          - unless booking.state == 'successful'
            %span.success
              |
              =button_to 'Mark as successful', admin_journey_booking_path(@journey, booking), { class: 'text', form_class: 'inline', method: 'put', remote: true, params: { 'booking[state]' => 'successful' } }
          - unless booking.state == 'missed'
            %span.missed
              |
              =button_to 'Mark as missed', admin_journey_booking_path(@journey, booking), { class: 'text', form_class: 'inline', method: 'put', remote: true, params: { 'booking[state]' => 'missed' } }
          
          %hr/
      %hr/
      %p= link_to 'Download runsheet', admin_journey_path(@journey, format: :csv), class: 'button'
      %hr/
      %h4 Send SMS message to
      = form_tag send_message_admin_journey_path(@journey) do
        = select_tag :to,                                                                                          |
          options_for_select([["All Passengers", "all"]] + @journey.bookings.collect {|x| [x.phone_number, x.id]}), |
          { class: 'select' } |
        = text_area_tag :notification_message
        = submit_tag "Send message"
        
:javascript

  $('.success form').on('ajax:success', function(e, data, status, xhr){
    $('.success').addClass('hidden');
  })
  
  $('.missed form').on('ajax:success', function(e, data, status, xhr){
    $('.missed').addClass('hidden');
  })

app/views/admin/journeys/surrounding_journeys.html.erb
Previous Journeys:
<% @previous_journeys.each do |journey| %>
  <%= journey.start_time %>
<% end %>
Next Journeys:
<% @next_journeys.each do |journey| %>
  <%= journey.start_time %>
<% end %>