config/routes.rb
Rails.application.routes.draw do
  get '/closure_notice', as: :closure_notice, to: 'notices#closure_notice'
  resources :log_entry, only: [:create]
  devise_for :suppliers, controllers: { registrations: "suppliers/registrations" }
  resources :places, only: [:index, :show]
  resources :promotion, only: [:index]
  resources :about, only: [:index]
  resources :suggest, only: [:index]
  resources :legal, only: [:index]
  resources :privacy, only: [:index]
  resources :unsubscribed, only: [:index]
  resources :journeys, only: [:index] do
    collection do
      get ':from/(:to)' => 'journeys#index', as: :from_to
      get ':from/:to/bookings/new' => 'bookings#new', as: :new_booking
      get ':from/:to/return' => 'journeys#return', as: :return
    end
  end
  resources :bookings, only: [:new, :create, :destroy] do
    collection do
      post :price
      post :passengers
      get :confirmation
      get :edit
      put :update
    end
    member do
      get :return_journeys
      put :send_missed_feedback
    end
  end
  
  resources :stops do
    resources :landmarks, only: [:index]
  end
  
  resources :routes

  root 'public#index'

  namespace :admin do
    get 'pending' => 'suppliers#pending'
    root 'journeys#index'
    #resource :team, only: [:show]
    resources :teams
    resources :pricing_rules
    get :account, to: 'teams#show'
    resources :journeys do
      collection do
        get 'surrounding_journeys'
      end
      member do
        post 'send_message'
      end
      resources :bookings, only: [:show, :update]
    end
    resources :bookings
    resources :suppliers
    resources :routes do
      member do
        put 'sort'
      end

      resources :stops
      resources :sub_routes
    end
    resources :suggestions
    resources :supplier_suggestions
    resources :promo_codes
    resources :bookings, only: :show
    resources :sms, only: [:new, :create]
    resources :places, only: [:new, :create]
    resources :placenames, only: [:index]
    resources :timetables
  end
  get '/admin' => 'admin/journeys#index', as: :supplier_root # creates user_root_path
  get '/bookings/:token/cancel', as: :cancel_booking, to: 'bookings#cancel'
  get '/bookings/cancelled', as: :booking_cancelled
  
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :route
  belongs_to :place, autosave: true, counter_cache: :route_count
  acts_as_list scope: :route
  has_many :pickup_stops, class_name: 'Booking', foreign_key: 'pickup_stop_id', dependent: :destroy
  has_many :dropoff_stops, class_name: 'Booking', foreign_key: 'dropoff_stop_id', dependent: :destroy
  has_many :landmarks, dependent: :destroy
  has_many :suggested_edit_to_stops, dependent: :destroy
  
  accepts_nested_attributes_for :landmarks, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :place, :route
  validate :check_landmarks
  
  after_create :queue_minutes_from_last_stop

  def previous_stops(reversed = false)
    if reversed
      route.stops.where('position >= ?', position)
    else
      route.stops.where('position <= ?', position)
    end
  end
  
  def previous_stop(reversed = false)
    if reversed
      route.stops.find_by(position: position + 1)
    else
      route.stops.find_by(position: position - 1)
    end
  end

  def minutes_from_first_stop(reversed = false)
    previous_stops(reversed).drop(1).sum { |s| s.try(:minutes_from_last_stop) || 0 }
  end

  def distance_to(stop)
    place.lat_lng.distance_to(stop.place.lat_lng, units: :miles)
  end
  
  def name
    place.name
  end

  def position_in_order(reversed: false)
    if reversed
      route.stops.count - position + 1
    else
      position
    end
  end
  
  def queue_minutes_from_last_stop
    CalculateMinutesFromLastStop.enqueue(id)
  end
  
  def check_landmarks
    if landmarks.size == 0
      self.errors.add :landmarks, 'You must specify at least one landmark'
    end
  end
  
  def copy
    stop = self.dup
    self.landmarks.each do |l|
      stop.landmarks << l.copy
    end
    stop.save
    stop
  end
  
end

app/controllers/admin/stops_controller.rb
class Admin::StopsController < AdminController
  before_action :find_route
  before_action :get_places, only: [:new, :edit, :create]
  
  def new
    @stop = @route.stops.new
    @back_path = admin_route_path(@route)
  end

  def create
    @stop = @route.stops.new(stop_params)
    
    if @stop.save
      if params[:commit] == "Create & add another stop"
        redirect_to new_admin_route_stop_path(@route)
      else
        redirect_to admin_route_path(@route)
      end
    else
      flash[:alert] = @stop.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @stop = @route.stops.find(params[:id])
    @back_path = admin_route_path(@route)
  end

  def update
    @stop = @route.stops.find(params[:id])
    @stop.update_attributes(stop_params)
    if @stop.valid?
      redirect_to admin_route_path(@route)
    else
      flash[:alert] = @stop.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @stop = @route.stops.find(params[:id])
    @stop.destroy
    redirect_to admin_route_path(@route)
  end


  private

  def stop_params
    params.require(:stop).permit(
      :place_id, :minutes_from_last_stop,
      landmarks_attributes: [:id, :name, :latitude, :longitude, :_destroy]
    )
  end

  def find_route
    @route = Route.find(params[:route_id])
  end
  
  def get_places
    @places = Place.all
  end
end

app/views/admin/stops/_fields.html.haml
= form.label :place_id
= form.select :place_id, options_for_select(@places.map { |p| [p.name, p.id, { 'data-lat' => p.latitude, 'data-lng' => p.longitude }] }, selected: @stop.place_id), {}, {class: 'select'}
= link_to 'Add a place', new_admin_place_path(previous_route_id: @route.id), id: 'new_place', class: 'button text', id: 'add-place'
%section.section
  %h3 Landmarks
  #landmarks
    - if @stop.landmarks.count > 0
      - @stop.landmarks.each do |landmark|
        = form.fields_for :landmarks, landmark do |builder|
          = render partial: 'admin/stops/landmark', locals: { f: builder, latitude: landmark.latitude, longitude: landmark.longitude }                                                 |
    - else
      %p#no_landmarks There are no landmarks
    = link_to_add_association "Add landmark", form, :landmarks, partial: 'admin/stops/landmark', class: 'text', render_options: { locals: { latitude: nil, longitude: nil }}
- content_for :js do
  :javascript
    jQuery.fn.extend({
      drawMap: function() {
        var $container = $(this);
        var $map = $container.find('.map')
        $map.uniqueId();
            
        var id = $map.attr('id');
        var coords = [$container.data('lat'), $container.data('lng')]
        var marker = L.marker(coords, {draggable:'true'});
        
        var map = L.map(id, {
          zoomControl: true
        }).setView(coords, 18);
        
      
        
        L.tileLayer('https://api.mapbox.com/styles/v1/wearefuturegov/cj8pp146j9uyv2rojanc93qtf/tiles/256/{z}/{x}/{y}?access_token={accessToken}', {
          maxZoom: 18,
          id: 'mapbox.streets',
          accessToken: 'pk.eyJ1Ijoid2VhcmVmdXR1cmVnb3YiLCJhIjoiY2o3dDc4bGpoNGd2ajJ3bWp4ZWg3dWd0YiJ9.SbUuzZNHrNFQmgjtYUTU-A'
        }).addTo(map);
        
        marker.on('dragend', function() {
          var position = marker.getLatLng();
          $container.find('.latitude').val(position.lat);
          $container.find('.longitude').val(position.lng);
        });
        
        marker.addTo(map);
      }
    });
    
    $('.landmark').each(function( index ) {
      $(this).drawMap();
    });
    
    $("#landmarks a.add_fields")
        .data("association-insertion-method", 'before')
        .data("association-insertion-node", 'this');
        
    $('#landmarks').on('cocoon:after-insert', function(e, insertedItem) {
      $('#no_landmarks').hide();
      insertedItem.data('lat', $('#stop_place_id').find(":selected").data('lat'));
      insertedItem.data('lng', $('#stop_place_id').find(":selected").data('lng'));
      insertedItem.drawMap();
    });

app/views/admin/stops/_landmark.html.haml
.landmark{"data-lat" => latitude, "data-lng" => longitude}
  %section.section
    = f.label :name
    = f.text_field :name
    .map{:style => "height: 300px; width: 100%;"}
    = f.hidden_field :latitude, class: 'latitude'
    = f.hidden_field :longitude, class: 'longitude'
    = link_to_remove_association 'Remove Landmark', f, class: 'text'

app/views/admin/stops/edit.html.haml
%section.section
  .card
    %h2 Edit stop
    = form_for [:admin, @route, @stop] do |form|
      = render partial: 'fields', locals: {form: form}
      .action.primary
        = form.submit "Save stop", :class => "button"
    = form_for [:admin, @route, @stop], method: :delete do |form|
      = form.submit "Delete stop", :class => "text"

app/views/admin/stops/new.html.haml
%section.section
  .card
    %h2 Add a stop
    = form_for [:admin, @route, @stop] do |form|
      = render partial: 'fields', locals: {form: form}
      .action
        = form.submit "Create & add another stop", :class => "button text"
      .action.primary
        = form.submit "Create & finish", :class => "button"