config/routes.rb
Rails.application.routes.draw do
  get '/closure_notice', as: :closure_notice, to: 'notices#closure_notice'
  resources :log_entry, only: [:create]
  devise_for :suppliers, controllers: { registrations: "suppliers/registrations" }
  resources :places, only: [:index, :show]
  resources :promotion, only: [:index]
  resources :about, only: [:index]
  resources :suggest, only: [:index]
  resources :legal, only: [:index]
  resources :privacy, only: [:index]
  resources :unsubscribed, only: [:index]
  resources :journeys, only: [:index] do
    collection do
      get ':from/(:to)' => 'journeys#index', as: :from_to
      get ':from/:to/bookings/new' => 'bookings#new', as: :new_booking
      get ':from/:to/return' => 'journeys#return', as: :return
    end
  end
  resources :bookings, only: [:new, :create, :destroy] do
    collection do
      post :price
      post :passengers
      get :confirmation
      get :edit
      put :update
    end
    member do
      get :return_journeys
      put :send_missed_feedback
    end
  end
  
  resources :stops do
    resources :landmarks, only: [:index]
  end
  
  resources :routes

  root 'public#index'

  namespace :admin do
    get 'pending' => 'suppliers#pending'
    root 'journeys#index'
    #resource :team, only: [:show]
    resources :teams
    resources :pricing_rules
    get :account, to: 'teams#show'
    resources :journeys do
      collection do
        get 'surrounding_journeys'
      end
      member do
        post 'send_message'
      end
      resources :bookings, only: [:show, :update]
    end
    resources :bookings
    resources :suppliers
    resources :routes do
      member do
        put 'sort'
      end

      resources :stops
      resources :sub_routes
    end
    resources :suggestions
    resources :supplier_suggestions
    resources :promo_codes
    resources :bookings, only: :show
    resources :sms, only: [:new, :create]
    resources :places, only: [:new, :create]
    resources :placenames, only: [:index]
    resources :timetables
  end
  get '/admin' => 'admin/journeys#index', as: :supplier_root # creates user_root_path
  get '/bookings/:token/cancel', as: :cancel_booking, to: 'bookings#cancel'
  get '/bookings/cancelled', as: :booking_cancelled
  
end

app/controllers/admin/timetables_controller.rb
class Admin::TimetablesController < AdminController
  
  before_action :get_routes, only: [:new, :edit]
  
  def index
    @timetables = Timetable.all
  end
  
  def new
    @timetable = Timetable.new
  end
  
  def create
    if Timetable.create(timetable_params)
      redirect_to admin_timetables_path
    else
      render :new
    end
  end
  
  def destroy
    @timetable = Timetable.find(params[:id])
    @timetable.destroy
    redirect_to admin_timetables_path
  end
  
  private
  
  def timetable_params
    params.require(:timetable).permit(
      :route_id,
      :team_id,
      :from,
      :to,
      :open_to_bookings,
      :reversed,
      days: [],
      timetable_times_attributes: [
        :time,
        :seats,
        stops: []
      ]
    )
  end
  
  def get_routes
    @routes = Route.where(route_id: nil)
  end

end

app/views/admin/timetables/_form.html.haml
= form_for [:admin, timetable] do |form|
  
  = form.label :route
  = form.select :route_id, options_from_collection_for_select(@routes, :id, :name, timetable.route_id), { include_blank: 'Please select a route' }, class: 'select'
  
  - if current_supplier.admin?
    = form.label :team_id, 'Team'
    = form.select :team_id, options_from_collection_for_select(Team.all, 'id', 'name'), { selected: current_team.id }, class: 'select'
  - else
    = form.hidden_field :team_id, value: current_team.id
  
  = form.label :from, 'Timetable Start Date'
  = form.date_select :from, { with_css_classes: true, order: [:day, :month, :year] }, { class: 'select' }
  
  = form.label :to, 'Timetable End Date'
  = form.date_select :to, { with_css_classes: true, order: [:day, :month, :year] }, { class: 'select' }
  
  = form.label :open_to_bookings, 'Open to Bookings?'
  = form.select :open_to_bookings, [['Yes', true], ['No', false]], {}, class: 'select'
  
  = form.label :reversed, 'Reversed?'
  = form.select :reversed, [['No', false], ['Yes', true]], {}, class: 'select'
  
  = form.label :days, 'Days of operation'
    
  - Date::DAYNAMES.each_with_index do |day, i|
    = label_tag do
      = check_box_tag "#{form.object_name}[days][]", i, timetable.days.map(&:to_s).include?(i.to_s)
      = day
  
  #time-wrapper{ class: timetable.timetable_times.count.zero? ? 'hidden' : '' }    
    #times{ 'data-route-id': timetable.route&.id }
      = form.fields_for :timetable_times do |time|
        = render 'timetable_time_fields', f: time
      .action.secondary
        = link_to_add_association 'add time', form, :timetable_times, { class: 'button secondary' }
  
  .action.primary
    = form.submit 'Submit', class: 'button border-bottom-radius'
  
- content_for :js do
  
  :javascript
    
    $('#timetable_route_id').change(function() {
      $('#time-wrapper').removeClass('hidden');
      $('#times').data('route-id', $(this).val())
    })
    
    $('#times').on('cocoon:after-insert', function(e, added_time) {
      var id = added_time.html().match(/timetable_timetable_times_attributes_(\d+)/)[1]
      var reversed = $('#timetable_reversed').val()
      added_time.attr('id', 'time-' + id)
      $.get('/admin/routes/' + $('#times').data('route-id') + '.js?time_id=' + id + '&reversed=' + reversed)
    })
    

app/views/admin/timetables/_timetable.html.haml
%tr
  %td=timetable.route&.name
  %td=timetable.from.to_date.to_s(&:short)
  %td=timetable.to.to_date.to_s(&:short)
  %td=link_to 'Delete timetable', admin_timetable_path(timetable), method: :delete, data: { confirm: 'This will delete all associated journeys. Are you sure?' }, class: 'button text'

app/views/admin/timetables/_timetable_time_fields.html.haml
.nested-fields
  %h2
    Time
  = f.time_select :time, { with_css_classes: true }, { class: 'select' }
  
  = f.label :seats, 'Available seats'
  = f.number_field :seats, class: 'input'
    
  %h3
    Stops
    
  .stops
    - if f.object.route.present?
      = render partial: 'admin/routes/stop', collection: @timetable.route.stops, locals: { selected: f.object.route.stops.collect(&:name), time_id: f.index }
  
  %p
    = link_to_remove_association 'Remove time', f

app/views/admin/timetables/index.html.haml
%section.section
  .card
    %h2
      Timetables
      
    %table.table
      %thead
        %tr
          %th Route
          %th Start Date
          %th End Date
          %th
      %tbody
        = render partial: 'timetable', collection: @timetables
    
    .action.primary
      = link_to 'Create new Timetable', new_admin_timetable_path, { class: 'button' }

app/views/admin/timetables/new.html.haml
%section.section
  .card
    %h2
      Add a new timetable
      
    = render 'form', timetable: @timetable