config/routes.rb
Rails.application.routes.draw do
  get '/closure_notice', as: :closure_notice, to: 'notices#closure_notice'
  resources :log_entry, only: [:create]
  devise_for :suppliers, controllers: { registrations: "suppliers/registrations" }
  resources :places, only: [:index, :show]
  resources :promotion, only: [:index]
  resources :about, only: [:index]
  resources :suggest, only: [:index]
  resources :legal, only: [:index]
  resources :privacy, only: [:index]
  resources :unsubscribed, only: [:index]
  resources :journeys, only: [:index] do
    collection do
      get ':from/(:to)' => 'journeys#index', as: :from_to
      get ':from/:to/bookings/new' => 'bookings#new', as: :new_booking
      get ':from/:to/return' => 'journeys#return', as: :return
    end
  end
  resources :bookings, only: [:new, :create, :destroy] do
    collection do
      post :price
      post :passengers
      get :confirmation
      get :edit
      put :update
    end
    member do
      get :return_journeys
      put :send_missed_feedback
    end
  end
  
  resources :stops do
    resources :landmarks, only: [:index]
  end
  
  resources :routes

  root 'public#index'

  namespace :admin do
    get 'pending' => 'suppliers#pending'
    root 'journeys#index'
    #resource :team, only: [:show]
    resources :teams
    resources :pricing_rules
    get :account, to: 'teams#show'
    resources :journeys do
      collection do
        get 'surrounding_journeys'
      end
      member do
        post 'send_message'
      end
      resources :bookings, only: [:show, :update]
    end
    resources :bookings
    resources :suppliers
    resources :routes do
      member do
        put 'sort'
      end

      resources :stops
      resources :sub_routes
    end
    resources :suggestions
    resources :supplier_suggestions
    resources :promo_codes
    resources :bookings, only: :show
    resources :sms, only: [:new, :create]
    resources :places, only: [:new, :create]
    resources :placenames, only: [:index]
    resources :timetables
  end
  get '/admin' => 'admin/journeys#index', as: :supplier_root # creates user_root_path
  get '/bookings/:token/cancel', as: :cancel_booking, to: 'bookings#cancel'
  get '/bookings/cancelled', as: :booking_cancelled
  
end

app/models/journey.rb
require 'csv'

class Journey < ApplicationRecord
  belongs_to :route
  has_many :stops, through: :route
  has_many :outward_bookings, dependent: :destroy, class_name: 'Booking', foreign_key: 'journey_id'
  has_many :return_bookings, dependent: :destroy, class_name: 'Booking', foreign_key: 'return_journey_id'
  has_many :bookings, dependent: :destroy, class_name: 'Booking'
  belongs_to :team
  validates_presence_of :team, :start_time, :route
  
  attr_accessor :pickup_stop, :dropoff_stop

  scope :forwards, -> {where("reversed IS NOT TRUE")}
  scope :backwards, -> {where("reversed IS TRUE")}
  scope :available, -> {where('start_time > :start_time AND open_to_bookings IS TRUE AND "full?" IS FALSE', start_time: Time.now)}

  scope :past_or_future, ->(past_or_future) {
    if past_or_future == 'past'
      where('start_time < ?', Time.now).order('start_time DESC')
    elsif past_or_future == 'future'
      where('start_time > ?', Time.now).order('start_time ASC')
    end
  }
  
  scope :on_date, ->(date) {
    where('start_time >= ? AND start_time <= ?', date.to_date.at_beginning_of_day, date.to_date.at_end_of_day)
  }
  scope :booked_or_empty, ->(booked_or_empty) {
    query = joins('LEFT JOIN bookings as outward_bookings on journeys.id = outward_bookings.journey_id LEFT JOIN bookings as return_bookings on journeys.id = return_bookings.return_journey_id').group('journeys.id')
    booked_or_empty == 'booked' ? query.having('count(outward_bookings) > 0 OR count(return_bookings) > 0') : query.having('count(outward_bookings) = 0 AND count(return_bookings) = 0')
  }
  scope :by_route, ->(route_id) {
    where(route_id: Route.id_with_subroutes(route_id))
  }

  filterrific(
    default_filter_params: {
      past_or_future: 'future'
    },
    available_filters: [
      :past_or_future,
      :on_date,
      :booked_or_empty,
      :by_route
    ]
  )
  
  after_create :close_before_end
  after_update :change_close_time, if: :saved_change_to_start_time?
  
  def self.available_for_places(start_place, destination_place)
    from = Stop.where(place: start_place)
    to = Stop.where(place: destination_place)
    routes = Route.where(id: from.collect(&:route_id) & to.collect(&:route_id)).includes(:stops)
    journeys = routes.map do |route|
      stops = route.stops
      f = from.find { |s| stops.include?(s) }
      t = to.find { |s| stops.include?(s) }
      Journey.available.where(
        route_id: route.id,
        reversed: f.position > t.position,
      ).pluck(:id)
    end.flatten.uniq
    Journey.where(id: journeys)
  end
  
  def duplicate(start_date, end_date, include_days = [0,1,2,3,4,5,6])
    (start_date..end_date).each do |date|
      next unless include_days.include?(date.wday)
      Journey.create(attributes.except('id').merge({
        'start_time' => "#{date.to_s}T#{start_time.strftime('%H:%M')}"
      }))
    end
  end

  def booked_bookings
    bookings.booked
  end

  def editable_by_supplier?(supplier)
    supplier.team == self.team
  end

  def is_booked?
    all_bookings.count > 0
  end

  def seats_left
    seats - booked_bookings.sum(:number_of_passengers)
  end

  def route_name
    "#{stops_in_direction.first.name} - #{stops_in_direction.last.name}"
  end

  def stops_in_direction
    reversed? ? stops.reverse : stops
  end
  
  def time_at_stop(stop)
    start_time + stop.minutes_from_first_stop(reversed?).minutes
  end
  
  def all_bookings
    outward_bookings.booked + return_bookings.booked
  end
  
  def csv
    CSV.generate do |csv|
      csv << csv_headers
      all_bookings.each do |booking|
        csv << booking.csv_row(id)
      end
    end
  end
  
  def csv_headers
    Booking.csv_headers + [
      'Outbound or Return',
      'Pickup Time',
      'Pickup Place',
      'Pickup Location',
      'Dropoff Time',
      'Dropoff Place',
      'Dropoff Location'
    ]
  end
  
  def filename
    [
      stops_in_direction.first.name.downcase,
      stops_in_direction.last.name.downcase,
      start_time.strftime('%F')
    ].join('-')
  end
  
  private
    
    def close_time
      if start_time.hour < 9
        (start_time - 1.day).change({ hour: 15, min: 30 })
      else
        start_time - 4.hours
      end
    end
    
    def close_before_end
      CloseBeforeEnd.enqueue(id, run_at: close_time)
    end
    
    def change_close_time
      QueJob.where("args::json->>0 = '?' AND job_class = 'CloseBeforeEnd'", id).destroy_all
      close_before_end
    end

end

app/controllers/admin/journeys_controller.rb
class Admin::JourneysController < AdminController
  before_action :find_journey, only: [:edit, :update, :destroy, :show, :send_message]
  before_action :check_permissions, except: [:index, :create, :new, :show, :surrounding_journeys]
  def index
    journeys = (current_supplier.admin? ? Journey.all : current_team.journeys).includes([:team, :route])
    @filterrific = initialize_filterrific(
      journeys,
      (params[:filterrific] || {})
    ) or return
    @journeys = @filterrific.find.page(params[:page])
    @routes = Route.main_routes
  end

  def new
    if params[:route_id]
      @route = Route.find(params[:route_id])
      @journey = current_team.journeys.new(route: @route, reversed: params[:reversed])
      @back_path = new_admin_journey_path
    else
      @back_path = admin_root_path
      render template: 'admin/journeys/new_choose_route'
    end
  end

  def create
    journey = Journey.create!(journey_params)
    redirect_to admin_journeys_path
  end

  def edit
    @back_path = admin_journey_path(@journey)
  end

  def show
    @back_path = admin_root_path
    respond_to do |format|
      format.html
      format.csv { send_data @journey.csv, filename: "#{@journey.filename}.csv", type: 'text/csv;charset=utf-8' }
    end
  end

  def update
    @journey.update_attributes(journey_params)
    redirect_to admin_journey_path(@journey)
  end

  def destroy
    @journey.destroy
    redirect_to admin_journeys_path
  end

  # TODO: What does this do? This should be moved to the RoutesController anyway
  def surrounding_journeys
    @route = Route.find(params[:route_id])
    @previous_journeys = @route.journeys.where('start_time < ?', params[:datetime]).order('start_time DESC').limit(2)
    @next_journeys = @route.journeys.where('start_time > ?', params[:datetime]).order('start_time ASC').limit(2)
    render layout: false
  end

  def send_message
    bookings = params[:to] == 'all' ? @journey.bookings : [ @journey.bookings.find(params[:to]) ]
    bookings.each do |booking|
      SendSMS.enqueue(to: booking.phone_number, message: params[:notification_message])
    end
    flash[:notice] = "Message sent!"
    redirect_to admin_journey_path(@journey)
  end

  private

  def journey_params
    params.require(:journey).permit(:start_time, :team_id, :route_id, :open_to_bookings, :reversed, :seats)
  end

  def find_journey
    @journey = Journey.find(params[:id])
  end

  def check_permissions
    unless @journey.editable_by_supplier?(current_supplier)
      render :file => "public/401.html", :status => :unauthorized
    end
  end
end

app/controllers/journeys_controller.rb
class JourneysController < PublicController
  before_action :find_places
  respond_to :html, :js
  
  def index
    if @from && @to
      @journeys = Journey.available_for_places(@from, @to)
      if @to.routes.count == 0 || @journeys.count == 0
        @possible_destinations = Place.possible_destinations(@from).uniq
        TrackFailedPlaceQuery.enqueue(@from.name, @to.name, DateTime.now.to_s)
      end
    end
  end
  
  def return
    start_time = DateTime.parse params[:start_time]
    @booking = Booking.new
    @journeys = Journey.available_for_places(@to, @from)
                       .where(start_time: start_time...start_time.end_of_day)
                       .order(:start_time)
  end
  
  private
  
    def journey_params
      params.permit(:from, :to)
    end
    
    def find_places
      @from = Place.friendly.find(journey_params[:from]) if journey_params[:from]
      @to = Place.friendly.find(journey_params[:to]) if journey_params[:to]
    end
  
end

app/views/journeys/_book_button.haml
- button_label ||= t('button.book')
= link_to button_label, new_booking_journeys_path(from.slug, to.slug), class: "button"

app/views/journeys/_form.html.haml
%section.section
  = label_tag do
    = t('journey.from.label')
  = text_field_tag :from, nil, placeholder: I18n.t('journey.from.message'), id: :from, value: from
  = label_tag do
    = t('journey.to.label')
  = text_field_tag :to, nil, placeholder: I18n.t('journey.to.message'), disabled: from.nil?, id: :to, value: to
  #from_result.hidden{"aria-live" => "assertive", :hidden => "", :role => "alert"}
    %p.error-block
      = t('message.sorry')
      from
      = succeed "." do
        %span#place
    %p
      %span.bold 
        = t('service')
      = t('message.feedback')
    %p
      = link_to I18n.t('button.typeform'), I18n.t('button.typeform-link')

app/views/journeys/_possible_destinations.html.haml
%div{"aria-live" => "assertive", :role => "alert"}
  %p.error-block
    = t('message.sorry')
    to <strong>#{to.name}</strong>.
  %p.small
    %span.bold
      = t('service')
    = t('message.feedback')
  %p
    = link_to I18n.t('button.typeform'), I18n.t('button.typeform-link')
  %p.small
    = t('message.other')
    <strong>#{from.name}</strong>
    = t('message.other_end')

  - places.each do |place|
    .single
      .details
        = render 'book_button', from: from, to: place, button_label: place.name

app/views/journeys/_return_times.html.haml
%section.section
  .times{ id: "return_times"}
    .direction
      %label.button.secondary.oneway
        = t('button.oneway')
        = form.radio_button :return_journey_id, nil
      %label.button.secondary.return.selected
        = t('button.return')
        = form.radio_button :return_journey_id, nil
      .hide_times
        - if journeys.length > 0
          %label
            = t('bookings.return.time')
          %p.time
            - journeys.each do |j|
              = render 'bookings/journey_time', journey: j, type: 'return', form: form, journey_type: :return_journey_id, from: j.stops.find_by(place: from), to: j.stops.find_by(place: to)
            
            - if journeys.map { |j| j.team.name }.uniq.include? 'TVN'
              %p
                %i If these timings are not suitable please contact #{link_to('01638 664304', 'tel:+441638664304')} to discuss your needs.
          .arrival-times.hidden
        - else
          .no-return-time
            = t('bookings.no_return_time')
    
:javascript
  
    $('#return_times .oneway').click(function() {
      $('#return_times .return').removeClass('selected');
      $('#return_times .oneway').addClass('selected');
      $('#return_times .hide_times').addClass('hide');
      $('.return_price').addClass('hidden');
      $('.single_price').removeClass('hidden');
      scrollToBottom();
    })

    $('#return_times .return').click(function() {
      $('#return_times .oneway').removeClass('selected');
      $('#return_times .return').addClass('selected');
      $('#return_times .hide_times').removeClass('hide');
      $('.single_price').addClass('hidden');
      $('.return_price').removeClass('hidden');
      scrollToBottom();
    })
    
    $('#return_times .oneway').click(function() {
      var to = $('#outward_times .button.selected input').data('toId');
      $('#booking_dropoff_stop_id').val(to);
      $.get('/stops/' + to + '/landmarks', { type: 'dropoff' }, function() {
        $('.landmarks').removeClass('hidden');
        scrollToBottom();
      });
    })

    $('#return_times .return').click(function() {
      $('.landmarks').addClass('hidden');
      scrollToBottom();
    })

    $('#return_times .time input').click(function() {
      var place = $('#start_location label').html();
      var data = $(this).data();
      $('#booking_dropoff_stop_id').val(data.toId);
      showArrivalTime(data, place);
      $.get('/stops/' + data.toId + '/landmarks', { type: 'dropoff' }, function() {
        $('.landmarks').removeClass('hidden');
        scrollToBottom();
      });
    })

    $('#return_times .button').on('click', function(){
      $('#return_times .hide_times .button').removeClass('selected');
      $(this).addClass('selected');
      scrollToBottom();
    });

app/views/journeys/_suggested_journeys.html.haml
%section.section
  %div{"aria-live" => "assertive", :role => "alert"}
    %p.error-block
      = t('message.sorry')
      <strong>#{from.name}</strong> to <strong>#{to.name}</strong>.
      = fa_icon 'exclamation-triangle'
    %p
      = t('message.suggest') 
      <strong>#{from.name}</strong>
      = t('message.suggest_end')
%section.section
  %h3
    = from.name
    %span
      to
    = fa_icon 'map-marker'
  - places.first(3).each do |place|
    .single
      .details
        %h3
          = link_to "#{place.name}", from_to_journeys_path(from.slug, place.slug), class: 'button'

app/views/journeys/index.html.haml
%section.section
  %h2
    = t('journey.title')

= render 'form', from: @from.try(:name), to: @to.try(:name)

%section.section
  #results
    - if @possible_destinations
      = render 'possible_destinations', places: @possible_destinations, from: @from, to: @to
    - elsif @journeys
      = render 'book_button', from: @from, to: @to

- content_for :js do

  :javascript
  
    // Monkey patch pushState to notify Google Analytics
    var pushState = history.pushState;
    history.pushState = function () {
      pushState.apply(history, arguments);
      if (typeof(ga) == 'function') {
        ga('set', 'location', arguments[2]);
        ga('send', 'pageview');
      }
    };
    
    var enableTo = function(slug) {
      var toOptions = options;
      $('#from').data('slug', slug);
      toOptions.list.onChooseEvent = chosenTo;
      $('#to').easyAutocomplete(toOptions);
    }
    
    var chosenFrom = function() {
      var chosenItem = $("#from").getSelectedItemData();
      $('#from').data('placename', chosenItem.name);
      $('#from_result').addClass('hidden');
      $('#from_result').attr('hidden', true);
      
      history.pushState(null, null, '/journeys/' + chosenItem.slug);
      
      if (chosenItem.route_count > 0) {
        enableTo(chosenItem.slug);
        $('#to').removeAttr('disabled');
      } else {
        var placename = $('#from').data('placename');
        $('#from_result #place').html(placename);
        $('#from_result').removeClass('hidden');
        $('#from_result').attr('hidden', false);
        $('#to').attr('disabled', 'true');
        $('#to').val('');
        $('#results').hide();
        $.post({
          url: '/log_entry/?from=' + chosenItem.name
        });
      }
    }
    
    var chosenTo = function() {
      var chosenItem = $("#to").getSelectedItemData();
      var url = '/journeys/' + $('#from').data('slug') + '/' + chosenItem.slug;

      $('#to').data('placename', chosenItem.name);
      $('#to_result').empty();
      
      history.pushState(null, null, url);
      
      
      
      $.get({
        url: url,
        dataType: 'script'
      });
      
      $('#results').show();
    }

    var options = {
      url: function(place) {
        return '/places.json?query=' + place
      },
      getValue: "name",
      list: {
        onChooseEvent: chosenFrom
      },
      theme: 'square'
    };
    
    window.onpopstate = function() {
      if (document.location.pathname == '/journeys') {
        $('#from').val('');
        $('#to').val('');
        $('#results').html('');
        $('#from_result').addClass('hidden');
        $('#from_result').attr('hidden', true);
      } else if (document.location.pathname.match(/journeys\/[a-z\-]+$/)) {
        $('#to').val('');
        $('#results').html('');
      }
    }

    $('#from').easyAutocomplete(options);
    
  - if @from
    - content_for :js do
      :javascript
        $(document).ready(function() {
          enableTo('#{ @from.try(:slug) }');
          $('#from').data('placename', '#{ @from.try(:name) }');
        });
      

app/views/journeys/index.js.erb
<% if @possible_destinations %>
  $('#results').html('<%= j(render 'possible_destinations', places: @possible_destinations, from: @from, to: @to) %>');
<% else %>
  $('#results').html('<%= j(render 'book_button', from: @from, to: @to) %>');
<% end %>

app/views/journeys/return.js.erb
<% form = ActionView::Helpers::FormBuilder.new('booking', @booking, self, {}) %>
$('#one_way').html('<%= j(render 'return_times', journeys: @journeys, form: form, from: @from, to: @to) %>');

app/views/journeys/suggested.html.erb
<div class='container'>
  <div class='inner'>
    <%= render 'form', from: @from.try(:name), to: @placename %>
    
    <div id="results">
      <%= render 'suggested_journeys', places: @places, from: @from, to: @placename %>
    </div>
  </div>
</div>

app/views/journeys/suggested.js.erb
$('#results').html('<%= escape_javascript(render 'suggested_journeys', places: @places, from: @from, to: @placename) %>');